---
# This broke and I'm not sure why. Doing it the stupid way...
- name: Register with RHN
  redhat_subscription:
    state: present
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
    autosubscribe: false

- name: Subscribe to pool
  command: "subscription-manager subscribe --pool {{ rhn_pool }}"

# Currently no support for repo manipulation in redhat_subscription module
- name: Disable all repos
  command: subscription-manager repos --disable="*"

- name: Enable OpenShift repos
  command: subscription-manager repos --enable="{{ item }}"
  with_items: "{{ repo_names }}"
