---
- name: install EPEL rpm
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present
  when: epel_from == "web"

- name: copy EPEL rpm
  file:
    src: "{{ epel_rpm }}"
    dest: /tmp/
  when: epel_from == "file"

- name: install EPEL rpm
  yum:
    name: "/tmp/{{ epel_rpm }}"
    state: present
  when: epel_from == "file"

- name: ensure EPEL directory esists
  file:
    path: "{{ docroot_dir }}/epel"
    state: directory

- name: sync EPEL repos (takes up to 60 minutes)
  command: "reposync -n -r epel -p {{ docroot_dir }}/epel"
  async: 3600
  poll: 60

- name: set up local EPEL repo
  command: "createrepo --database {{ docroot_dir }}/epel/epel"