---
- name: make the GitLab directory
  file:
    name: "{{ docroot_dir }}/gitlab"
    state: directory
    recurse: yes

- name: download the GitLab rpm
  shell: "curl -LJO {{ gitlab_url }} > {{ gitlab_rpm }}"
#    creates: "{{ docroot_dir }}/gitlab/{{ gitlab_rpm }}"
  args:
    chdir: "{{ docroot_dir }}/gitlab"

- name: set up the GitLab repo
  command: "createrepo --database {{ docroot_dir }}/gitlab"