---
- name: make the GitLab directory
  file:
    name: "{{ docroot_dir }}/gitlab"
    state: directory
    recurse: yes

# There's something funky with how GitLab delivers their RPMs, probably
# including an http redirect. So for now we'll skip this, since I can't brain
# and we'll just grab the rpm from s3 instead. But this sucks and it's a pain
# to update.
- name: download the GitLab rpm
  get_url:
    url: "{{ gitlab_url }}"
    dest: "{{ docroot_dir }}/gitlab/{{ gitlab_rpm }}"
    mode: 0644
    owner: root
  when: not gitlab_s3

- name: download the GitLab rpm from S3
  get_url:
    url: "{{ gitlab_s3_url }}"
    dest: "{{ docroot_dir }}/gitlab/{{ gitlab_rpm }}"
    mode: 0644
    owner: root
  when: gitlab_s3

- name: set up the GitLab repo
  command: "createrepo --database {{ docroot_dir }}/gitlab"

- name: install git client
  yum:
    name: git
    state: present

- name: clone all the GitHub repos
  command: "git clone --recursive {{ item }}"
  args:
    chdir: "{{ docroot_dir }}/gitlab"
  with_items:
    - "{{ github_repos }}"